# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
      - run: yarn build

      - name: Save target
        uses: actions/upload-artifact@v2
        with:
          name: target
          retention-days: 1
          path: |
            docs
            target
            flow-typed
            typings
            buildstamp.json
  test:
    name: Test (Node v${{ matrix.node-version }})
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      matrix:
        node-version: [12, 14]
    steps:
      - uses: actions/checkout@v1
      - name: Restore target
        uses: actions/download-artifact@v2
        with:
          name: target
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn test
      - name: Push coverage
        if: matrix.node-version == '14'
        uses: actions/upload-artifact@v2
        with:
          name: target
          retention-days: 1
          path: coverage

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Restore target
        uses: actions/download-artifact@v2
        with:
          name: target
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Codeclimate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/*.lcov:lcov

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extends: |
            @qiwi/semrel-config
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: 'mailbox@antongolub.ru'
          GIT_COMMITTER_EMAIL: 'mailbox@antongolub.ru'
          GIT_AUTHOR_NAME: '@antongolub'
          GIT_COMMITTER_NAME: '@antongolub'
