# Skip commits with [skip ci] / [ci skip] directives
name: ci-init
on: [push, pull_request]
jobs:
  init:
    name: init
    runs-on: ubuntu-20.04
    outputs:
      skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
      skip-not: ${{ steps.ci-skip-step.outputs.ci-skip-not }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: ci-skip-step
        uses: mstachniuk/ci-skip@v1

  build:
    name: build
    needs: init
    if: ${{ needs.init.outputs.skip == 'false' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn
      - run: yarn build

      - name: Save target
        uses: actions/upload-artifact@v2
        with:
          name: target
          retention-days: 1
          path: |
            docs
            target
            flow-typed
            typings
            buildstamp.json
