# Trigger semantic-release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    # https://github.community/t/trigger-job-on-tag-push-only/18076
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test_push
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Restore target
        uses: actions/download-artifact@v2
        with:
          name: target
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Codeclimate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/*.lcov:lcov

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extends: |
            @qiwi/semrel-config
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: 'mailbox@antongolub.ru'
          GIT_COMMITTER_EMAIL: 'mailbox@antongolub.ru'
          GIT_AUTHOR_NAME: '@antongolub'
          GIT_COMMITTER_NAME: '@antongolub'
